apparmor: false
arch:
- aarch64
- amd64
description: Grafana Tempo is an open source, easy-to-use, and high-scale distributed
  tracing backend.
homeassistant_api: true
image: ghcr.io/cedricziel/{arch}-addon-grafana-tempo
init: false
map:
- share:rw
name: Grafana Tempo
options:
  prometheus_url: http://24212397-mimir:8001/api/v1/push
ports:
  14268/tcp: null
  3200/tcp: null
  4317/tcp: null
  4318/tcp: null
  9095/tcp: null
  9411/tcp: null
ports_description:
  14268/tcp: Jaeger/Thrift HTTP
  3200/tcp: Tempo
  4317/tcp: OTLP/gRPC
  4318/tcp: OTLP/HTTP
  9095/tcp: gRPC
  9411/tcp: Zipkin
schema:
  prometheus_url: str
slug: tempo
url: https://github.com/cedricziel/ha-addon-grafana-tempo/blob/main/tempo
version: 5b243f2
watchdog: http://[HOST]:3200/ready
